services:
  webapi:
    build:
      context: ./backend  # Указываем папку backend как контекст
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_VERSION=8.0
      - ConnectionStrings__DefaultConnection=Server=db;Database=PrimLabDB;User=sa;Password=Password123!;TrustServerCertificate=True;
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend/angular-app
    ports:
      - "4200:80"
    depends_on:
      webapi:
        condition: service_started

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P Password123! -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
    ports:
      - "1433:1433"
    #volumes:
    #  - type: bind
    #    source: ./mssql_data
    #    target: /var/opt/mssql

volumes:
  sql_data:
    driver_opts:
        type: none
        device: ./mssql_data
        o: bind